os: ubuntu 
language: generic
before-install: 
  - sudo apt-get install g++ 
  - sudo apt-get install gcc 
  - sudo apt-get install bison 
  - sudo apt-get install flex 
  - sudo apt-get install libarchive-zip-perl 
  - sudo apt-get install libcups2-dev
  - sudo apt-get install libpam0g-dev
  - sudo apt-get install gperf 
  - sudo apt-get install libfreetype6-dev 
  - sudo apt-get install install libxaw7-dev 
  - sudo apt-get install libfontconfig1-dev 
  - sudo apt-get install libxrandr-dev patch
  - sudo apt-get install libgconf2-dev 
  - sudo apt-get install libgnomevfs2-dev 
  - sudo apt-get install ant 
  - sudo apt-get install libgtk2.0-dev 
  - sudo apt-get install junit 
  - sudo apt-get install junit4 
  - sudo apt-get install 
  - sudo apt-get install libidl-dev 
  - sudo apt-get install liborbit2-dev
script:
  - cd aoo/main
  - autoconf
  - ./configure <configure_switches>
  - ./bootstrap
  - source *.set.sh
  - cd instsetoo_native
  - build --all

