branches:
  only:
    - test

language: minimal

install:
  - sudo apt-get install g++ gcc bison flex libarchive-zip-perl libcups2-dev libpam0g-dev gperf libfreetype6-dev libxaw7-dev libfontconfig1-dev libxrandr-dev patch libgconf2-dev libgnomevfs2-dev ant libgtk2.0-dev junit junit4 libidl-dev liborbit2-dev

script:
  - cd main
  - autoconf
  - ./configure
  - ./bootstrap
  - source *.set.sh
  - cd instsetoo_native
  - build --all
