language: generic
dist: bionic
sudo: true


script:
  - chmod +x install.sh
  - ./install.sh

before_script:
  - autoconf
  - ./configure --with-dmake-url=https://sourceforge.net/projects/oooextras.mirror/files/dmake-4.12.tar.bz2 --with-epm-url=https://sourceforge.net/projects/oooextras.mirror/files/epm-3.7.tar.gz
  - ./bootstrap
  - shopt -s expand_aliases
  - source LinuxX86-64Env.Set.sh
  - cd instsetoo_native
  
  
script:
  -build --from util --prepare
