language: generic
dist: bionic
sudo: true

jdk:
  - openjdk11
  - openjdk-ea

matrix:
  allow_failures:
    - jdk: openjdk-ea

script:
  - chmod +x install.sh
  - ./install.sh
  - cd main/instsetoo_native/util/ && make
