language: minimal
sudo: true
dist: bionic

git:
  autocrlf: input

deploy:
  provider: releases
  api_key: 702bafbeb4b9c69f21aae0fcf337f39c1e84629b
  file: script.sh
  skip_cleanup: true
  draft: true
