language: generic
dist: bionic
sudo: true

jdk:
  - openjdk11
  - openjdk-ea

matrix:
  allow_failures:
    - jdk: openjdk-ea

before_script:
  - autoconf
  - ./configure --with-dmake-url=https://sourceforge.net/projects/oooextras.mirror/files/dmake-4.12.tar.bz2 --with-epm-url=https://sourceforge.net/projects/oooextras.mirror/files/epm-3.7.tar.gz
  - ./bootstrap
  
script:
  - chmod +x install.sh
  - ./install.sh
